services:
  db:
    image: postgres:16
    container_name: flexibooker-db
    environment:
      POSTGRES_DB: flexibooker
      POSTGRES_USER: flexi
      POSTGRES_PASSWORD: flexi_pw
    ports:
      - "5432:5432"
    volumes:
      - flexibooker_pg:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: flexibooker-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin_pw
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  flexibooker_pg:
